[package]
edition = "2024"
name = "abs_cancel"
version = "0.2.0"

description = "ABStraction of Cancellation"
repository = "https://gitee.com/lino_snsalias/abs_cancel-rs"
keywords = ["async", "traits"]
categories = ["no-std"]
license = "MIT/Apache-2.0"

[dev-dependencies]
compio = { version = "0.19.*", features = ["fs", "macros", "time"] }
